### ISSUE TITLE
pushing code from computer to gihub repository

### ISSUE THREAD

**Issue by chaitu0101** [githubschool/on-demand-github-pages#1752]
I have developed an application in my local ide( eclipse) and i would like to push that application into my git hub account. i am unable to do that because i dont know the process,. I googled regarding that , they suggested to click on local repository but i did not found that option. please hel me out.

**Comment by crichID** [comment]
@chaitu0101 welcome ---  here are the steps you will need to follow:

1. Create an empty repository on GitHub under the name of the project. (be sure you do not check the box to create a README).
   - GitHub will provide a remote URL for the project, something like `https://github.com/YOUR_USER/YOUR_PROJECT.git`
2. Since it is an existing project, it will be easiest to initialize it from the command line. Follow these instructions to do so:
   - Open your command line application (Git Bash on Windows)
   - cd into the project directory
   - type `git init`
   - type `git remote add origin REMOTE_URL` <-- this is the URL GitHub provided when you created the repository
   - at this point, you may want to [consider adding a .gitignore file](https://help.github.com/articles/ignoring-files/)
   - type `git add .`
   - type `git  commit -m "initializing project"`
   - type `git push -u origin master`
3. Once you have completed these steps your project will be available on GitHub and you will be able to start using the eGit plugin locally to create branches,  etc.  For more information on using Git with Eclipse, check out this webcast: https://vimeo.com/233553151/a82c0af051

**Comment by chaitu0101** [comment]
Thank you for responding.

It helped a lot.
