### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by NicholasAnaya** [githubschool/on-demand-github-pages#1905]
I keep getting this error when I type git push ::

 ERROR: Permission to learn-co-students/swift-mathBoolOp-lab-swift-intro-000.git denied to NicholasAnaya.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by brianamarie** [comment]
Hi @NicholasAnaya! Make sure that you're in the correct repository, and that you are authenticated properly. 

Since this question doesn't relate to this course, I'm going to direct you to [GitHub Support](https://github.com/contact). The GitHub Support team is FANTASTIC, and they will be able to get back to you quickly and help point you in the right direction. Good luck!
