### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by don-montgomery** [githubschool/on-demand-github-pages#2530]
Hi, I went through the "publish webpage" lesson, chose a theme, chose a source (master), committed the default text to master, and then went to don-montgomery.github.io and then don-montgomery.github.io/REPONAME to see the results, but I got a 404 in both cases, what am I doing wrong?  Please help me, @githubteacher !!!

Thanks, Don

**Comment by beebus** [comment]
@don-montgomery ,

I took a look at your issue.
Going to [http://don-montgomery.github.io/](http://don-montgomery.github.io/) indeed gives a 404 error, "There isn't a GitHub Pages site here."

You have 3 repositories, one of which I think is misspelled, [https://github.com/don-montgomery/don-montgomery.githhub.io](https://github.com/don-montgomery/don-montgomery.githhub.io), possibly causing this issue. There is an extra "h" in the name of the repository. It should be titled ...github.io instead of githhub.io.
