### ISSUE TITLE
Request for push access

### ISSUE THREAD

**Issue by malam04** [githubschool/on-demand-github-pages#2829]
I need push access! @githubteacher

**Comment by beebus** [comment]
We keep getting the same Travis CI error:

![Screenshot from 2019-09-03 04-48-42](https://user-images.githubusercontent.com/3438663/64163382-c31b9080-ce06-11e9-9916-554ce79c22d5.png)

$ rvm use **2.2.2** --install --binary --fuzzy
$ export BUNDLE_GEMFILE=$PWD/Gemfile
ruby.versions
$ ruby --version
install.bundler
58.19s$ bundle install --jobs=3 --retry=3 --deployment
before_script.1
1.84s$ pip install --user yamllint
before_script.2
1.23s$ pip install --user yamale
1.38s$ **gem install html-proofer**
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: mini_portile2-2.4.0.gem (100%)
Successfully installed mini_portile2-2.4.0
Fetching: **nokogiri-1.10.4.gem** (100%)
ERROR:  Error installing html-proofer:
	**The last version of nokogiri (~> 1.9) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1` and then running the current command again
	nokogiri requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
The command "gem install html-proofer" failed and exited with 1 during .**

Possible solutions:
1. Increase the ruby version to 2.3.0 in the .travis.yml file so that nokogiri installs correctly and html-proofer installs correctly.
2. Do not install html-proofer.
3. It's ambiguous whether or not installing an earlier version of nokogiri, `gem install nokogiri -v 1.9.1` before installing html-proofer, would resolve the situation. Nokogiri might always need Ruby version >= 2.3.0 now.

A normal user / collaborator will not have the permissions to make these change(s). This change would have to be made by an owner or admin of the repo.
