### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Itstorro** [githubschool/on-demand-github-pages#2969]
My itstorro-add-page branch to the on-demand-github-pages didn't pass the Travis CI tests, why?

**Comment by Itstorro** [comment]
How do I edit the offending file in my branches

**Comment by RascalTwo** [comment]
I'm not familur with the project, but I am familur with YAML.

You're getting two errors related to your `pages/Itstorro.yaml` file:

- no new line character at the end of file  (new-line-at-end-of-file)
- syntax error: mapping values are not allowed here

*****

The first one is easy, add a newline to the end of the file.

*****

The second one is caused by the `—` characters surrounding your content:

```yaml
—
githubHandle: itstorro
pageUrl: itstorro.github.io
timestamp: 2018-05-07
—
```

I assume your editor automatically converted your three hyphens - `---` - to this, so replacing `—` with `---` should make your YAML valid.

**Comment by Itstorro** [comment]
Thanks! I'll try that out

**Comment by beebus** [comment]
It looks like it was successful, yes? 
If so, go ahead and close the issue.
