### ISSUE TITLE
CI test fails due to botoxny.github.io 404

### ISSUE THREAD

**Issue by borzumate** [githubschool/on-demand-github-pages#546]
Pull request #545 is failing due to test failing with error:

`External link botoxny.github.io failed: 404 No error`

**Comment by r5atom** [comment]
Same issue here #542 
It seems botoxny's website has disappeared causing the check to fail.  

Is it very rude to remove `on-demand-github-pages/_pages/botoxny.yaml` ?

**Comment by r5atom** [comment]
Since you are on your own branch (e.g. `UserName-add-page`) I should be safe to edit file `on-demand-github-pages/_pages/botoxny.yaml` in that branch.

Replacing the URL might be a work-around.
* Replace the URL that causes an 404 error (in this case `botoxny.github.io`) with an URL that *does* exist (e.g. `github.com`)
* Commit the two files (your .yaml and the repaired file)
* Merge with `master`. When trying to merge there might be conflicts that needs to be addressed first. The current `master` might not have the same "spoofed" URL for instance.

Agreed @brianamarie?

**Comment by hectorsector** [comment]
👋 @borzumate @r5atom thanks for noticing! You are correct about what's going on here. It looks like @brianamarie replaced the URL with a standard `github.com` in https://github.com/githubschool/on-demand-github-pages/pull/551 so I'll go ahead and close this out now.

**Comment by hectorsector** [comment]
I should've also mentioned, that if any open PRs are lying around still reflecting the 404's URL, we can just do a reverse merge fro master, and that should grab the changes from #551.
